-- Generated by generate_enemy_tracking.py; do not edit by hand.
-- Source: silent-destroyer/tunic-randomizer 26dab1bde90903d3475ce9c590abc25b71f9322e
-- Source table: tunic/combat_logic.py area_data
-- Combat areas: 19

COMBAT_AREA_DATA = {
    ["overworld"] = {1, 1, 1, 1, 1, 1, 0, {"Stick"}, false},
    ["east_forest"] = {1, 1, 1, 1, 1, 1, 0, {"Sword"}, false},
    ["before_well"] = {1, 1, 1, 1, 1, 1, 3, {"Sword", "Shield"}, false},
    ["beneath_the_well"] = {2, 1, 3, 3, 1, 1, 3, {"Sword", "Shield"}, false},
    ["dark_tomb"] = {2, 2, 3, 3, 1, 1, 3, {"Sword", "Shield"}, false},
    ["west_garden"] = {2, 3, 3, 3, 1, 1, 4, {"Sword", "Shield"}, false},
    ["garden_knight"] = {3, 3, 3, 3, 2, 1, 4, {"Sword", "Shield"}, true},
    ["beneath_the_vault"] = {3, 3, 3, 3, 2, 1, 4, {"Sword", "Shield", "Magic"}, false},
    ["eastern_vault_fortress"] = {3, 3, 3, 4, 3, 2, 4, {"Sword", "Shield", "Magic"}, false},
    ["siege_engine"] = {3, 3, 3, 4, 3, 2, 4, {"Sword", "Shield", "Magic"}, true},
    ["frogs_domain"] = {3, 4, 3, 5, 3, 3, 4, {"Sword", "Shield", "Magic"}, false},
    ["ruined_atoll"] = {4, 4, 3, 5, 3, 3, 5, {"Sword", "Shield", "Magic"}, false},
    ["librarian"] = {4, 4, 3, 5, 3, 3, 5, {"Sword", "Shield", "Magic"}, true},
    ["quarry"] = {5, 4, 3, 5, 3, 3, 5, {"Sword", "Shield", "Magic"}, false},
    ["rooted_ziggurat"] = {5, 5, 3, 5, 3, 3, 6, {"Sword", "Shield", "Magic"}, false},
    ["boss_scavenger"] = {5, 5, 3, 5, 3, 3, 6, {"Sword", "Shield", "Magic"}, true},
    ["swamp"] = {1, 1, 1, 1, 1, 1, 6, {"Sword", "Shield", "Magic"}, false},
    ["gauntlet"] = {1, 1, 1, 1, 1, 1, 6, {"Sword", "Shield", "Magic"}, true},
    ["heir"] = {5, 5, 3, 5, 3, 3, 6, {"Sword", "Shield", "Magic", "Laurels"}, true},
}
